#!/bin/bash
# Powered by Apad.pro
# https://apad.pro/easymosdns
#
# Notes: EasyMosDNS for CentOS/RedHat 7+
#
mosdns_working_dir="/etc/mosdns"
source $mosdns_working_dir/include.conf
sed -i '/^            - forward_host_socks/c\            - forward_tunadns' $mosdns_working_dir/config.yaml
#sed -i '/^            - forward_googledns/c\            - forward_tunadns' $mosdns_working_dir/config.yaml
sed -i '/^            - forward_googledns_socks/c\            - forward_tunadns' $mosdns_working_dir/config.yaml
sed -i '/^            - forward_easymosdns/c\            - forward_tunadns' $mosdns_working_dir/config.yaml
sed -i '/^            - forward_tunadns/c\            - forward_tunadns' $mosdns_working_dir/config.yaml
$mosdns_working_dir/restart.service
echo 'RemoteServer:TUNADNS(DoH)'