#!/bin/bash
# Powered by Apad.pro
# https://apad.pro/easymosdns
#
# Notes: EasyMosDNS for CentOS/RedHat 7+
#
mosdns_working_dir="/etc/mosdns"
source $mosdns_working_dir/include.conf
sed -i '/^        #- ecs_auto/c\        - ecs_auto' $mosdns_working_dir/config.yaml
sed -i '/^            # - ecs_auto/c\            - ecs_auto' $mosdns_working_dir/config.yaml
sed -i '/^            #- ecs_global/c\            - ecs_global' $mosdns_working_dir/config.yaml
$mosdns_working_dir/restart.service
echo 'ECS:On'