#!/bin/bash
# Powered by Apad.pro
# https://apad.pro/easymosdns
#
# Notes: EasyMosDNS for CentOS/RedHat 7+
#
mosdns_working_dir="/etc/mosdns"
mkdir -p /tmp/easymosdns && curl https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt > /tmp/easymosdns/china_domain_list.txt && curl https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt > /tmp/easymosdns/gfw_domain_list.txt && curl https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt > /tmp/easymosdns/china_ip_list.txt && curl https://raw.githubusercontent.com/bigdargon/hostsVN/master/source/hosts.txt | sed '/^#/d; s/0.0.0.0 //' > /tmp/easymosdns/temp_hosts && cat /tmp/easymosdns/temp_hosts /tmp/easymosdns/china_domain_list.txt | sort | uniq -d > /tmp/easymosdns/temp_china_hosts && cat /tmp/easymosdns/temp_hosts /tmp/easymosdns/temp_china_hosts | sort | uniq -u > /tmp/easymosdns/ad_domain_list.txt && \cp -rf /tmp/easymosdns/*.txt $mosdns_working_dir/rules && rm -rf /tmp/easymosdns/* && echo 'update successful'